services:
  weblate:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: web
  weblate-celery-backup:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-backup
  weblate-celery-beat:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    environment:
      WEBLATE_SERVICE: celery-beat
  weblate-celery-celery:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-celery
  weblate-celery-memory:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-memory
  weblate-celery-notify:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-notify
  weblate-celery-translate:
    image: pilate
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: weblate-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - weblate-celery-beat
    environment:
      WEBLATE_SERVICE: celery-translate
  database:
    image: postgres:17-alpine
    env_file:
    - ./environment
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:7-alpine
    restart: always
    read_only: true
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
